
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*                  INTERNAL HEADER FILE FOR OBJECT DUMMY                      */
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/

/*-------------*/
/* Name of DLL */
/*-------------*/
#define DLL_NAME        "DUMMY"
 
/*----------------------*/
/* Name of Help library */
/*----------------------*/
#define HELP_LIB        "DUMMY.HLP"

/*------------------------------------------*/
/* Imbed of the dialog resource header file */
/*------------------------------------------*/
#include "dummyd.h"


/*---------------------------------*/
/* Window identifier               */
/*---------------------------------*/

#define ID_MAIN               100


/*---------------------------------*/
/* String identifiers              */
/*---------------------------------*/

#define STR_TITLE             200
#define STR_NOTYET            201


/*---------------------------------*/
/* Action bar identifiers          */
/*---------------------------------*/
#define MN_FILE                10  
#define MN_FILENEW             11
#define MN_FILEOPEN            12
#define MN_FILEEXIT            13

#define MN_OPTIONS             20
#define MN_OPTIONSDIALOG1      21               
                                     

/*---------------------------------*/
/* Symbolic names for Help support */
/*---------------------------------*/
#define DUMMY_HELPTABLE         1000
#define HID_MAIN                1000
#define SUBTABLE_MAIN           1100
#define HMN_FILENEW             1111
#define HMN_FILEOPEN            1112
#define HMN_FILEEXIT            1113
#define HDIALOG                 2000
#define SUBTABLE_DIALOG         2100
#define HEF_DUMMY               2111
 
